<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.UserIndexResponse</code>
 */
class UserIndexResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 err = 1;</code>
     */
    protected $err = 0;
    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     */
    protected $msg = '';
    /**
     * 返回一个 UserEntity 对象的列表数据
     *
     * Generated from protobuf field <code>repeated .user.UserEntity data = 3;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $err
     *     @type string $msg
     *     @type \User\UserEntity[]|\Google\Protobuf\Internal\RepeatedField $data
     *           返回一个 UserEntity 对象的列表数据
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 err = 1;</code>
     * @return int
     */
    public function getErr()
    {
        return $this->err;
    }

    /**
     * Generated from protobuf field <code>int32 err = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setErr($var)
    {
        GPBUtil::checkInt32($var);
        $this->err = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>string msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     * 返回一个 UserEntity 对象的列表数据
     *
     * Generated from protobuf field <code>repeated .user.UserEntity data = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * 返回一个 UserEntity 对象的列表数据
     *
     * Generated from protobuf field <code>repeated .user.UserEntity data = 3;</code>
     * @param \User\UserEntity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \User\UserEntity::class);
        $this->data = $arr;

        return $this;
    }

}

